[workspace]
members = [
    "edgedb-derive",
    "edgeql-parser",
    "edgeql-python",
    "edgeql-pytest",
    "edgedb-protocol",
    "edgedb-repl",
    "edgedb-server",
]

[profile.release]
debug = true
lto = true
