[package]
name = "edgedb-protocol"
license = "MIT/Apache-2.0"
version = "0.1.0"
authors = ["MagicStack Inc. <hello@magic.io>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
snafu = {version="0.6.0"}
uuid = "0.8.1"
num-bigint = {version="0.2.3", optional=true}
num-traits = {version="0.2.10", optional=true}
bigdecimal = {version="0.1.0", optional=true}

[features]
default = []
num_bigint_types = ["num-bigint", "num-traits"]
bigdecimal_types = ["bigdecimal", "num-bigint", "num-traits"]
all-types = ["num_bigint_types", "bigdecimal_types"]

[lib]
