[package]
name = "edgedb-protocol"
version = "0.1.0"
authors = ["MagicStack Inc. <hello@magic.io>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
snafu = {version="0.6.0"}
uuid = "0.8.1"
bigdecimal = "0.1.0"

[lib]
