[package]
name = "edgedb-repl"
version = "0.1.0"
authors = ["MagicStack Inc. <hello@magic.io>"]
edition = "2018"

[dependencies]
edgedb-protocol = {path = "../edgedb-protocol"}
snafu = {version="0.6.0", features=["backtraces"]}
anyhow = "1.0.23"
async-std = {version="1", features=[
    # we need stdin/stdout and channel
    "unstable",
]}
bytes = "0.4.12"
rustyline = { git="https://github.com/gwenn/rustyline", rev="86cb6f5" }


[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"

[[bin]]
name = "edgedb"
path = "src/main.rs"
