on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --exclude edgeql-pytest
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p edgeql-python
      - working-directory: ./edgedb-protocol
        run: |
          cargo test --no-default-features
      - uses: actions-rs/cargo@v1
        env:
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.0/x64/lib
        with:
          command: test
          args: -p edgeql-pytest
